### ISSUE TITLE
Error Unknown command "dev"

### ISSUE THREAD

**Issue by ulivz** [open-source-labs/OverVue#75]
Following the instructions:

```
npm i -g @quasar/cli
npm i
quasar dev -m electron
```

I got error:

```
 Error Unknown command "dev"


  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|


  Running @quasar/cli v1.0.0
```

**Comment by ulivz** [comment]
?

**Comment by deanfchung** [comment]
https://github.com/quasarframework/quasar/issues/3965

**Comment by ulivz** [comment]
![image](https://user-images.githubusercontent.com/23133919/62414677-4d7aa400-b651-11e9-914e-6dff5d294b9d.png)

**Comment by ajmas** [comment]
Providing an answer here for anyone else who comes across this:

Typically this happens because the current project is either not a Quasar project or needs upgrading. The `quasar` command will show different options depending on whether you in a Quasar project or not. A 

Steps to try:

  - Ensure the project packages are installed:

`yarn run install`

  - If still no luck, then you can try upgrading:

`quasar upgrade`

This has worked for me in the past. Good luck.

**Comment by Akash-Preet** [comment]
![2020-02-11_08h29_04](https://user-images.githubusercontent.com/16293043/74208294-eba69100-4ca8-11ea-8b27-54e1eda3ce8e.png)

I tried running `yarn install` and `npm install` before executing `quasar dev`

**Comment by ajmas** [comment]
@Akash-Preet did you run `quasar upgrade` again following the ‘yarn install’, since the first time it yielded an error.

**Comment by JojuOlaode** [comment]
@Akash-Preet let us know if you are still running across this error. We just did a major version update so you might want to consider moving over to OverVue 2.0. I can look into this issue as well but it seems like @ajmas gave a good response.

**Comment by lucho19jose** [comment]
common mistake is when you aren't in the currently directory where you istalled. so you should enter to the proyect just then run "quasar dev"

**Comment by Abuabdelah** [comment]
after installing `@quasar/app` & `@quasar/extras` worked again for me.
