### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by AustinGil** [open-source-labs/OverVue#91]
Hi, Im wondering if you plan to provide support for Linux users?

Im sure there arent so many of us, but hopefully it's not so hard. I would love to see that happen, but also have no expectations.

**Comment by matteociasco** [comment]
+1

**Comment by lucarossi93** [comment]
+1

**Comment by mattiaiacoucci01** [comment]
+1

**Comment by entioentio** [comment]
+1

**Comment by ZermattChris** [comment]
Yes please! Mint 20 👍😎

**Comment by elisabethschwartz** [comment]
+1

**Comment by InfoSec812** [comment]
Oh, wow, it's even easier than I thought. Since the developers are using [Quasar Framework](https://quasar.dev/) it's a simple command to build the Electron app for Linux.

1. Clone the repo
2. From the root of the project, run `npm install`
3. Build the electron app `npx @quasar/cli build -m electron`
4. Use `electron-packager` to create RPM/DEB/FlatPak/Snap packages

Dang! I **LOVE** Quasar Framework

**Comment by AustinGil** [comment]
Can confirm that @InfoSec812's solution above works well enough. Running up through the third step will produce a /dist folder with some options including AppImage. Nice!

**Comment by katherinek123** [comment]
Hello! The recent version of OverVue supports Linux! Check out overvue.org.
